---
galaxy_info:
  role_name: zsh
  author: andreigusev
  description: Install zsh and oh-my-zsh for users with a zsh shell
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions:
        - noble
dependencies: []
